#!/bin/bash

export GIT_ROOTDIR=$(git rev-parse --show-toplevel)
export DTR_NAMESPACE=doevelopper
export RND_NS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
export DEV_ENV=$(basename $(git rev-parse --show-toplevel))

# start docker and emacs
#docker run -d \
#    --volume $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
#    -p 5000:5000 \
#    --memory="500m" \
#    --memory-swap="1g" \
#    --env DISPLAY=${DISPLAY} \
#    --net="host" \
#    --volume $XAUTHORITY:/developer/.Xauthority \
#    -e DISPLAY \
#    --env XAUTHORITY=/developer/.Xauthority \
#    --env SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
#    --device /dev/snd \
#    --volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
#    --user $(id -u ${USER}):$(id -g ${USER}) \

docker run  --rm -ti \
    --volume ${PWD}/project:/project \
    --volume ${HOME}/.conan:/home/developer/.conan:rw \
    --volume ${HOME}/.ssh:/home/developer/.ssh:rw \
    --volume ${PWD}/src/main/resources/dotfiles/.vim:/home/developer/.vim:rw \
    --volume ${HOME}/.m2:/home/developer/.m2:rw \
    --volume ${PWD}/dotfiles/.vimrc:/home/developer/.vimrc \
    --volume ${PWD}/dotfiles/.bashrc:/home/developer/.bashrc  \
    --volume "$PWD:/home/developer/workspace" \
    --name cfs-edac-vscode \
    --privileged doevelopper/cfs-com-common:0.0.1

run_container() {
	GIT_ROOTDIR=$(git rev-parse --show-toplevel) \
	DTR_NAMESPACE=doevelopper \
	RND_NS=$(shell cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1) \
	CONTAINER="doevelopper/cfs-com-"$1 \
	docker run --rm \
		--memory=$(($(head -n 1 /proc/meminfo | awk '{print $2}') * 4 / 5))k \
		--cpus=$((`nproc` - 1))
		--log-opt max-size=50m  \
		--volume $(GIT_ROOTDIR)/src/main/resources/dotfiles/.vim:/home/${DTR_NAMESPACE}/.vim \
		--volume $(GIT_ROOTDIR)/src/main/resources/dotfiles/.vimrc:/home/${DTR_NAMESPACE}/.vimrc \
		--volume $(GIT_ROOTDIR)/src/main/resources/dotfiles/.bashrc:/home/${DTR_NAMESPACE}/.bashrc \
		--volume $(GIT_ROOTDIR):/home/${DTR_NAMESPACE}/workspace \
		--volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
		--volume ${HOME}/.conan:/home/${DTR_NAMESPACE}/.conan \
		--volume ${HOME}/.ssh:/home/${DTR_NAMESPACE}/.ssh \
		--volume ${HOME}/.Xauthority:/root/.Xauthority \
		--volume ${HOME}/.m2:/home/${DTR_NAMESPACE}/.m2 \
		--volume /etc/passwd:/etc/passwd:ro \
		--env DISPLAY=unix${DISPLAY}
		--env LANG=C.UTF-8
		--env LC_ALL=C.UTF-8
		--env DOCKER_USER=`id -un`
		--env DOCKER_USER_ID=`id -u`
		--env DOCKER_PASSWORD=`id -un`
		--env DOCKER_GROUP_ID=`id -g`
		--name="$(PWD)-$(RND_NS)-$(date +'%Y%m%d-%H%M%S')"
		--hostname="$(PWD)-$(RND_NS)"
		--tty --interactive $(CONTAINER):latest
}

# --entrypoint "urxvt" \
# alternatively, you can map your settings into the container
# docker run -it \
#        -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
#        -v $XAUTHORITY:/developer/.Xauthority \
#        -v ${HOME}/.config/Code:/developer/.config/Code \
#        -v ${HOME}/.vscode:/developer/.vscode \
#        -v ${HOME}/.ssh:/developer/.ssh \
#        -v ${HOME}/.gitconfig:/developer/.gitconfig \
#        -v ${PWD}/project:/project \
#        -v ${SSH_AUTH_SOCK}:/ssh_auth_sock \
#        -e SSH_AUTH_SOCK=/ssh_auth_sock \
#        -e DISPLAY=unix${DISPLAY} \
#        -e XAUTHORITY=/developer/.Xauthority \
#        -p 5000:5000 \
#        --device /dev/snd \
#        --name docker-vscode \
#        --entrypoint "xterm" \
#        registry.gear.ge.com/100034251/ide:latest

#docker exec docker-vscode /developer/bin/start-vscode
#docker exec docker-vscode /developer/bin/start-emacs


