#         cfs-com/.gitlab/ci/applycations-deployment.yml
#
#               Copyright (c) 2014-2018 A.H.L
#
#        Permission is hereby granted, free of charge, to any person obtaining
#        a copy of this software and associated documentation files (the
#        "Software"), to deal in the Software without restriction, including
#        without limitation the rights to use, copy, modify, merge, publish,
#        distribute, sublicense, and/or sell copies of the Software, and to
#        permit persons to whom the Software is furnished to do so, subject to
#        the following conditions:
#
#        The above copyright notice and this permission notice shall be
#        included in all copies or substantial portions of the Software.
#
#        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#        NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#        LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#        OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#        WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

deploy to staging:
    stage: Install to local staging repository
    before_script:
        - echo "Deploy to $ENVS ($CI_JOB_NAME in $CI_JOB_STAGE)"
    script:
        - cicd/deploy $CI_ENVIRONMENT_NAME
    environment:
        name: staging
        url:  https://dashboard.acme/status?id=staging/
    when: manual
    only:
        # executes the build on every push to the branch: 
        - master
    except:
        - branches
    artifacts:
        expire_in: 1d
        paths:
            - "*.zip"

deploy to production:
    stage: Deploy artifacts to staging repositories
    before_script:
        - echo "Deploy to $ENVS ($CI_JOB_NAME in $CI_JOB_STAGE)"
    script:
        - cicd/deploy $CI_ENVIRONMENT_NAME
    environment:
        name: production
        url:  https://dashboard.acme/status?id=production
    when: manual
    only:
        # executes the build on every push to the branch: 
        - master
        - tags
        - /^v\d+\.\d+\.\d+$/
        - /^v\d+\.\d+(\.\d+)?($|-)/
        -/^v\d+\.\d+(\.\d+)?($|-)/
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
        - /^v\d+\.\d+\.\d+(?:(?:(?:\+|\.)?[a-zA-Z0-9]+)*)?$/
        - /^v\d+\.\d+\.\d+(?:-(?:beta|rc)(?:(?:(?:\+|\.)?[a-zA-Z0-9]+)*)?)?$/
    except:
        - branches
    artifacts:
        expire_in: 1d
        paths:
            - "*.zip"
            - "*.tgz"
