#         cfs-com/.gitlab/ci/applications-review.yml
#
#               Copyright (c) 2014-2018 A.H.L
#
#        Permission is hereby granted, free of charge, to any person obtaining
#        a copy of this software and associated documentation files (the
#        "Software"), to deal in the Software without restriction, including
#        without limitation the rights to use, copy, modify, merge, publish,
#        distribute, sublicense, and/or sell copies of the Software, and to
#        permit persons to whom the Software is furnished to do so, subject to
#        the following conditions:
#
#        The above copyright notice and this permission notice shall be
#        included in all copies or substantial portions of the Software.
#
#        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#        NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#        LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#        OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#        WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Open Merge Request:
#    image: tmaier/gitlab-auto-merge-request
    before_script: []      # We do not need any setup work, let's remove the global one (if any)
    variables:
        GIT_STRATEGY: none # We do not need a clone of the GIT repository to create a Merge Request
    when: manual
    stage: Code review
    only:
        - /^feature\/*/    # We have a very strict naming convention
    script:
        - >
            HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} 
            GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./autoMergeRequest.sh
            
        - merge-request.sh # The name of the script

#Courtesy to https://rpadovani.com/open-mr-gitlab-ci
Open Merge Request:
#    image: tmaier/gitlab-auto-merge-request
    before_script: []      # We do not need any setup work, let's remove the global one (if any)
    variables:
        GIT_STRATEGY: none # We do not need a clone of the GIT repository to create a Merge Request
    when: manual
    stage: code-review
    only:
        - /^feature\/*/    # We have a very strict naming convention
    script:
        - >
            HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} 
            GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./autoMergeRequest.sh
            
        - merge-request.sh # The name of the script